# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('slug', models.SlugField(verbose_name='Url \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438')),
                ('managers', models.ManyToManyField(related_name='company_manager', to='auth.Group')),
            ],
        ),
    ]
