# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='company_manager', to='auth.Group'),
        ),
    ]
