# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images//%Y/%m/%d'),
        ),
    ]
